import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { mkdirSync, mkdtempSync, rmSync, utimesSync, writeFileSync } from "fs";
import { tmpdir } from "os";
import path from "path";
import {
  claudeProjectDir,
  claudeProjectDirs,
  claudeProjectSlug,
  claudeSessionExists,
  isClaudeSessionId,
  listClaudeSessions,
  readClaudeSession,
  resetClaudeSessionCaches,
} from "./claude-sessions";

const CWD = "/home/user/My_App";
const ID = (n: number) => `00000000-0000-4000-8000-${String(n).padStart(12, "0")}`;

let config: string;
const savedEnv = process.env.CLAUDE_CONFIG_DIR;

beforeEach(() => {
  config = mkdtempSync(path.join(tmpdir(), "cm-claude-config-"));
  process.env.CLAUDE_CONFIG_DIR = config;
  resetClaudeSessionCaches();
});

afterEach(() => {
  rmSync(config, { recursive: true, force: true });
  if (savedEnv === undefined) delete process.env.CLAUDE_CONFIG_DIR;
  else process.env.CLAUDE_CONFIG_DIR = savedEnv;
});

type Line = Record<string, unknown> | string;

const user = (content: unknown, extra: Record<string, unknown> = {}) => ({ type: "user", cwd: CWD, message: { role: "user", content }, ...extra });
const assistant = (id: string, text = "ok") => ({ type: "assistant", cwd: CWD, message: { id, role: "assistant", content: [{ type: "text", text }] } });

/** Writes a conversation file; `age` in minutes sets its mtime. */
function conversation(id: string, lines: Line[], { age = 0, dir = claudeProjectSlug(CWD) }: { age?: number; dir?: string } = {}): string {
  const d = path.join(config, "projects", dir);
  mkdirSync(d, { recursive: true });
  const file = path.join(d, `${id}.jsonl`);
  writeFileSync(file, lines.map((l) => (typeof l === "string" ? l : JSON.stringify(l))).join("\n") + "\n");
  const t = new Date(Date.UTC(2026, 9, 8, 12, 0, 0) - age * 60_000);
  utimesSync(file, t, t);
  return file;
}

describe("paths", () => {
  it("slugs the cwd like Claude Code and honours CLAUDE_CONFIG_DIR", () => {
    expect(claudeProjectSlug("/home/user/CodeMaestro")).toBe("-home-user-CodeMaestro");
    expect(claudeProjectSlug("/home/user/my_app.v2")).toBe("-home-user-my-app-v2");
    expect(claudeProjectDir("/home/user/CodeMaestro")).toBe(path.join(config, "projects", "-home-user-CodeMaestro"));
  });

  it("recognises session ids", () => {
    expect(isClaudeSessionId(ID(1))).toBe(true);
    expect(isClaudeSessionId("1F98C0AE-0277-576F-9A1B-EA6CDE8A1553")).toBe(true);
    expect(isClaudeSessionId("not-a-uuid")).toBe(false);
    expect(isClaudeSessionId(`../${ID(1)}`)).toBe(false);
    expect(isClaudeSessionId(undefined)).toBe(false);
  });
});

describe("listClaudeSessions", () => {
  it("lists conversations newest first with the first real prompt as title", async () => {
    conversation(ID(1), [user("Älteres Thema"), assistant("m1")], { age: 60 });
    conversation(
      ID(2),
      [
        { type: "queue-operation", operation: "enqueue", content: "ignored" },
        user("<command-name>/clear</command-name>"),
        user("Caveat: The messages below were generated by the user while running local commands."),
        user("<local-command-stdout></local-command-stdout>"),
        user("meta text", { isMeta: true }),
        user([{ type: "tool_result", tool_use_id: "t1", content: "x" }]),
        user("Subagent prompt", { isSidechain: true }),
        user([
          { type: "text", text: "<system-reminder>ctx</system-reminder>" },
          { type: "text", text: "  Baue den   Login\n neu  " },
        ]),
        assistant("m2", "a"),
        assistant("m2", "b"), // same API response, second block
        "{not json",
        assistant("m3"),
      ],
      { age: 5 }
    );
    const list = await listClaudeSessions(CWD);
    expect(list.map((s) => s.id)).toEqual([ID(2), ID(1)]);
    expect(list[0]).toEqual({ id: ID(2), title: "Baue den Login neu", updatedAt: "2026-10-08T11:55:00.000Z", messageCount: 3 });
    expect(list[1].title).toBe("Älteres Thema");
  });

  it("prefers a rename over the AI title over the first prompt", async () => {
    conversation(ID(1), [user("Prompt"), assistant("m"), { type: "ai-title", aiTitle: "KI-Titel" }, { type: "custom-title", customTitle: "Mein Name" }]);
    conversation(ID(2), [user("Prompt"), assistant("m"), { type: "ai-title", aiTitle: "Alt" }, { type: "ai-title", aiTitle: "KI-Titel neu" }], { age: 1 });
    conversation(ID(3), [{ type: "summary", summary: "Zusammenfassung", leafUuid: "x" }, user([{ type: "image" }]), assistant("m")], { age: 2 });
    expect((await listClaudeSessions(CWD)).map((s) => s.title)).toEqual(["Mein Name", "KI-Titel neu", "Zusammenfassung"]);
  });

  it("ignores other files, foreign folders sharing the slug, and empty or sidechain-only conversations", async () => {
    conversation(ID(1), [user("Echt"), assistant("m")]);
    conversation(ID(2), [{ ...user("Anderer Ordner"), cwd: "/home/user/My-App" }, assistant("m")]);
    conversation(ID(3), [user("nur Subagent", { isSidechain: true }), { ...assistant("m"), isSidechain: true }]);
    conversation(ID(4), [{ type: "summary", summary: "nur Zusammenfassung" }]);
    conversation(ID(5), ["garbage", ""]);
    const dir = path.join(config, "projects", claudeProjectSlug(CWD));
    writeFileSync(path.join(dir, "agent-1234.jsonl"), JSON.stringify(user("x")));
    writeFileSync(path.join(dir, `${ID(6)}.txt`), JSON.stringify(user("x")));
    mkdirSync(path.join(dir, `${ID(7)}.jsonl`));
    expect((await listClaudeSessions(CWD)).map((s) => s.id)).toEqual([ID(1)]);
  });

  it("skips CodeMaestro's own orchestrator runs", async () => {
    const internal = [
      "You are an orchestration planner for a coding assistant working in the directory /x.",
      "You are the conductor of a small team of AI coding agents",
      "You orchestrated multiple AI workers on this task:",
      "You are the Reviewer on this team. Check it.",
      "Review the work with fresh eyes",
      "You are reviewing the changes",
      "Address the review findings below",
    ];
    internal.forEach((p, i) => conversation(ID(10 + i), [user(`  ${p}`), assistant(`m${i}`)], { age: i }));
    conversation(ID(1), [user("you are the best – fix the login"), assistant("m")], { age: 30 });
    expect((await listClaudeSessions(CWD)).map((s) => s.id)).toEqual([ID(1)]);
  });

  it("caps the list and fills it past skipped files", async () => {
    for (let i = 0; i < 6; i++) conversation(ID(i), [user(`Thema ${i}`), assistant(`m${i}`)], { age: i * 2 });
    conversation(ID(99), [user("Review the work"), assistant("r")], { age: 1 });
    const list = await listClaudeSessions(CWD, { limit: 3 });
    expect(list.map((s) => s.title)).toEqual(["Thema 0", "Thema 1", "Thema 2"]);
  });

  it("reads only the head and tail of a large file", async () => {
    const big = "x".repeat(4000);
    const filler = Array.from({ length: 150 }, (_, i) => assistant(`b${i}`, big));
    conversation(ID(1), [user("Großes Projekt"), ...filler, { type: "ai-title", aiTitle: "Titel am Ende" }]);
    const [info] = await listClaudeSessions(CWD);
    expect(info.title).toBe("Titel am Ende");
    expect(info.messageCount).toBeUndefined();
  });

  it("finds a project dir by the recorded cwd when the slug dir is missing (hashed long paths)", async () => {
    conversation(ID(1), [user("Lang"), assistant("m")], { dir: `${claudeProjectSlug(CWD).slice(0, 10)}-abc123` });
    conversation(ID(2), [{ ...user("Fremd"), cwd: "/elsewhere" }, assistant("m")], { dir: "-elsewhere" });
    expect(await claudeProjectDirs(CWD)).toEqual([path.join(config, "projects", `${claudeProjectSlug(CWD).slice(0, 10)}-abc123`)]);
    expect((await listClaudeSessions(CWD)).map((s) => s.id)).toEqual([ID(1)]);
  });

  it("returns nothing when Claude Code has no data", async () => {
    expect(await listClaudeSessions(CWD)).toEqual([]);
    process.env.CLAUDE_CONFIG_DIR = path.join(config, "missing");
    expect(await listClaudeSessions(CWD)).toEqual([]);
  });
});

describe("claudeSessionExists / readClaudeSession", () => {
  it("only accepts a listed conversation of this folder", async () => {
    conversation(ID(1), [user("Weiter so"), assistant("m")]);
    conversation(ID(2), [user("Review the work"), assistant("m")]);
    conversation(ID(3), [user("x"), assistant("m")], { dir: "-other" });
    expect(await claudeSessionExists(CWD, ID(1))).toBe(true);
    expect((await readClaudeSession(CWD, ID(1)))?.title).toBe("Weiter so");
    expect(await claudeSessionExists(CWD, ID(2))).toBe(false);
    expect(await claudeSessionExists(CWD, ID(3))).toBe(false);
    expect(await claudeSessionExists(CWD, ID(4))).toBe(false);
    expect(await claudeSessionExists(CWD, `../-other/${ID(3)}`)).toBe(false);
    expect(await claudeSessionExists("/home/user/other", ID(1))).toBe(false);
  });
});
