import { describe, expect, it } from "vitest";
import type { PromptExample, PromptStructured } from "@/lib/ai/types";
import { builtInTemplates } from "@/lib/templates/built-in";
import { buildXml } from "./xml-builder";
import { PROMPT_TAGS, parseXml, parseXmlPartial, tagPattern } from "./xml-parser";
import { techniques } from "./techniques";

const base: PromptStructured = {
  instructions: "",
  context: "",
  constraints: "",
  examples: [],
  task: "",
  targetAudience: "",
  outputFormat: "",
};

const ex = (input: string, thinking: string, answer: string, id = "x"): PromptExample => ({
  id,
  input,
  thinking,
  answer,
});

/** Example ids are regenerated by the parser and undefined keys don't matter. */
function normalize(s: PromptStructured) {
  const examples = s.examples.map((e) => ({ input: e.input, thinking: e.thinking, answer: e.answer }));
  const out: Record<string, unknown> = { ...s, examples };
  for (const k of Object.keys(out)) if (out[k] === undefined) delete out[k];
  return out;
}

/** parse(build(x)) must equal x, and stay a fixed point over several rounds. */
function expectRoundTrip(x: PromptStructured, rounds = 3) {
  let cur = x;
  for (let i = 0; i < rounds; i++) {
    const back = parseXml(buildXml(cur));
    expect(normalize(back), `round ${i + 1}`).toEqual(normalize(x));
    cur = back;
  }
}

// Multi-line value with every character the builder must escape, user
// indentation, blank lines and already-escaped-looking literals.
const ML =
  "Line 1 with R&D <b>bold</b> & \"quotes\" 'single'\n  indented line 2\n\n    deeper line 4 > x && y < z\nlast &amp; literal &lt;tag&gt; text";

describe("buildXml → parseXml round trip", () => {
  it("single-line fields", () => {
    expectRoundTrip({ ...base, instructions: "Do it", context: "ctx", task: "t", targetAudience: "devs", outputFormat: "md" });
  });

  it("special characters and tag-like text", () => {
    expectRoundTrip({
      ...base,
      instructions: "A & B < C > D \"q\" 'a' &amp; &lt; &#38;",
      task: "</task> <instructions>inject</instructions>",
    });
  });

  it("multi-line values in every top-level field", () => {
    expectRoundTrip({ ...base, instructions: ML, context: ML, constraints: ML, targetAudience: ML, outputFormat: ML, task: ML });
  });

  it("indented first lines and tabs", () => {
    expectRoundTrip({ ...base, constraints: "  - a\n  - b\n    - nested", task: "\tTabbed first\n\tTabbed second" });
  });

  it("examples, including multi-line and code", () => {
    expectRoundTrip({
      ...base,
      instructions: "x",
      examples: [
        ex("in & <out>", "Step 1: a\n  Step 1a: b\nStep 2: \"c\"", ML, "1"),
        ex("only input", "", "single answer", "2"),
        ex("code:\n```ts\nif (a < b && c > d) {\n  return \"x\";\n}\n```", "", "ok", "3"),
      ],
    });
  });

  it("swarm config with escaped attributes", () => {
    expectRoundTrip({
      ...base,
      instructions: "x",
      swarmConfig: {
        topology: "mesh",
        coordinationStrategy: "byzantine",
        memoryScope: "local",
        agentCount: 7,
        agentRoles: [
          { type: "researcher", name: 'R&D "Lead" <1>', description: 'Finds & reads <docs> "carefully"' },
          { type: "custom", name: "Agent 'two'", description: "multi\nline description" },
        ],
      },
    });
  });

  it.each(techniques.map((t) => [t.id]))("technique %s", (id) => {
    expectRoundTrip({ ...base, instructions: "x", technique: id });
  });

  it("everything at once", () => {
    expectRoundTrip({
      ...base,
      instructions: ML,
      context: "c & c",
      constraints: "- a\n- b",
      task: "t <x>",
      targetAudience: "A",
      outputFormat: 'JSON {"a": 1}',
      examples: [ex(ML, ML, ML)],
      technique: "few-shot-cot",
      swarmConfig: {
        topology: "ring",
        coordinationStrategy: "weighted",
        memoryScope: "user",
        agentCount: 1,
        agentRoles: [{ type: "coder", name: "C&C", description: "a<b" }],
      },
    });
  });

  it("closing-tag literals inside values", () => {
    expectRoundTrip({
      ...base,
      instructions: "a </instructions> b",
      task: "</task>",
      examples: [ex("</input>\n</example></examples>", "</thinking></reasoning-approach>", "</answer>")],
      swarmConfig: {
        topology: "star",
        coordinationStrategy: "majority",
        memoryScope: "project",
        agentCount: 1,
        agentRoles: [{ type: "tester", name: 'n"></agent>', description: "</agent></swarm-config>" }],
      },
    });
  });

  it.each(builtInTemplates.map((t) => [t.slug, t.content]))("built-in template %s is a fixed point", (_slug, content) => {
    const parsed = parseXml(content);
    // A template must actually carry a prompt, not parse to nothing.
    expect(parsed.instructions || parsed.task).toBeTruthy();
    expectRoundTrip(parsed);
  });
});

describe("buildXml output", () => {
  it("renders long context first and the task last", () => {
    const xml = buildXml({ ...base, instructions: "i", context: "c", constraints: "k", outputFormat: "o", task: "t", technique: "react" });
    const order = [...xml.matchAll(/^<([a-z-]+)[\s>]/gm)].map((m) => m[1]);
    expect(order[0]).toBe("context");
    expect(order[order.length - 1]).toBe("task");
  });

  it("renders the technique as its name only", () => {
    for (const t of techniques) {
      const xml = buildXml({ ...base, instructions: "x", technique: t.id });
      expect(xml).toContain(`<technique>${t.name.replace(/&/g, "&amp;")}</technique>`);
      expect(xml).not.toContain(t.description);
    }
    // Prompts saved with "Name — description" still parse.
    expect(parseXml("<instructions>x</instructions>\n<technique>Self-Refine — old description</technique>").technique).toBe("self-refine");
  });

  it("keeps tags from snippets literal, so the model reads them as written", () => {
    const x: PromptStructured = {
      ...base,
      context: '<documents>\n  <document index="1">\n    <source>a.md</source>\n  </document>\n</documents>\nError output:\n<pasted_content id="r4nd">\nboom\n</pasted_content id="r4nd">',
      instructions: "Output <promise>DONE</promise> only when `a && b` holds; R&D uses Vec<String>. Answer in <answer> tags.",
      constraints: "<verification>\nRun the tests.\n</verification>",
      task: "x < y > z",
    };
    const xml = buildXml(x);
    for (const literal of ["<promise>DONE</promise>", "a && b", "R&D", "Vec<String>", "<answer> tags", "<verification>", '<pasted_content id="r4nd">', "x < y > z"]) {
      expect(xml).toContain(literal);
    }
    expect(xml).not.toMatch(/&lt;|&gt;|&amp;/);
    expectRoundTrip(x);
  });

  it("escapes only what the parser would read as structure or decode", () => {
    const x: PromptStructured = {
      ...base,
      instructions: 'Mention </instructions> and <TASK a="1"> and <output_format>; literal &lt; &amp; &#60; stay, &AMP; too',
      task: "real task",
      examples: [ex("q with <answer>x</answer> and </example>", "m <input>", "a </examples>")],
    };
    const xml = buildXml(x);
    expect(xml.match(/<task>/g)).toHaveLength(1);
    expect(xml).toContain("&lt;TASK a=\"1\"&gt;");
    expect(xml).toContain("&amp;lt; &amp;amp; &amp;#60;");
    expect(xml).toContain("&AMP;");
    expect(xml).toContain("q with &lt;answer&gt;x&lt;/answer&gt;");
    expectRoundTrip(x);
  });

  it("round-trips randomly mixed markup, entities and whitespace", () => {
    const tokens = [
      "<", ">", "&", "&amp;", "&lt;", "&AMP;", "&#60;", "&#x3C;", "&#99999999;", "<task>", "</task>", "</Task >", "<task\n>",
      '<task a="1">', "<output_format>", "<examples>", "</example>", "<input>", "</answer>", "<method>", "<thinking>",
      "</swarm_config>", "<agent>", "<technique>", "<context>", "<promise>DONE</promise>", '</pasted_content id="x">',
      "Vec<String>", "a && b", "<inputs>", "</", "<task", " ", "\n", "\n  ", "\t", "word", "{{CHECK_COMMAND}}", '"',
    ];
    let seed = 7;
    const next = (n: number) => {
      seed = (seed * 1103515245 + 12345) & 0x7fffffff;
      return seed % n;
    };
    const text = () => Array.from({ length: next(10) }, () => tokens[next(tokens.length)]).join("").trim();
    for (let i = 0; i < 300; i++) {
      // Values are trimmed: edge whitespace is normalised by design.
      const examples = next(2) ? [ex(text(), text(), text())].filter((e) => e.input || e.answer) : [];
      expectRoundTrip(
        { ...base, instructions: text(), context: text(), constraints: text(), task: text(), targetAudience: text(), outputFormat: text(), examples },
        2
      );
    }
  });
});

describe("example reasoning rendering", () => {
  it("does not render example reasoning as a <thinking> section", () => {
    // <thinking> sections risk reasoning_extraction refusals on Claude 5.x.
    const xml = buildXml({ ...base, instructions: "x", examples: [ex("q", "approach", "a")] });
    expect(xml).toContain("approach");
    expect(xml).not.toMatch(/<thinking[\s>]/i);
  });

  it("omits the reasoning tag when an example has none", () => {
    const xml = buildXml({ ...base, instructions: "x", examples: [ex("q", "", "a")] });
    const example = xml.match(/<example>([\s\S]*?)<\/example>/)?.[1] ?? "";
    expect(example.match(/<[a-z-]+>/g)).toEqual(["<input>", "<answer>"]);
  });

  it("parses legacy <thinking> examples into example.thinking", () => {
    const legacy = [
      "<instructions>Do X</instructions>",
      "<examples>",
      "  <example>",
      "    <input>Q</input>",
      "    <thinking>",
      "      Step 1: look",
      "        detail",
      "    </thinking>",
      "    <answer>A</answer>",
      "  </example>",
      "</examples>",
    ].join("\n");
    const parsed = parseXml(legacy);
    expect(parsed.examples).toHaveLength(1);
    expect(parsed.examples[0]).toMatchObject({ input: "Q", thinking: "Step 1: look\n  detail", answer: "A" });
    // Re-building uses the current tag and stays stable from then on.
    expectRoundTrip(parsed);
  });

  it("parses every built-in template's examples with their reasoning", () => {
    for (const t of builtInTemplates) {
      const parsed = parseXml(t.content);
      for (const e of parsed.examples) {
        expect(e.input || e.answer, t.slug).toBeTruthy();
      }
    }
  });
});

describe("parseXml on loose input", () => {
  it("AI-style XML with surrounding prose", () => {
    const parsed = parseXml(
      "Here you go:\n<instructions>\nDo X\n</instructions>\n<context>  Ctx  </context>\n<examples>\n<example>\n<input>Q</input>\n<thinking>\nStep 1\n    </thinking>\n<answer>A</answer>\n</example>\n</examples>\n<task>T &amp; U</task>"
    );
    expect(normalize(parsed)).toEqual(
      normalize({ ...base, instructions: "Do X", context: "Ctx", task: "T & U", examples: [ex("Q", "Step 1", "A")] })
    );
  });

  it("prompt wrapped in <prompt> and a code fence", () => {
    const parsed = parseXml(
      "```xml\n<prompt>\n  <instructions>\n    You are X.\n    - a\n      - nested\n  </instructions>\n  <context>Ctx</context>\n  <examples>\n    <example>\n      <input>\n        Q1\n        Q2\n      </input>\n      <answer>A</answer>\n    </example>\n  </examples>\n  <task>\n    T\n  </task>\n</prompt>\n```"
    );
    expect(normalize(parsed)).toEqual(
      normalize({
        ...base,
        instructions: "You are X.\n- a\n  - nested",
        context: "Ctx",
        examples: [ex("Q1\nQ2", "", "A")],
        task: "T",
      })
    );
  });

  it("CRLF line endings", () => {
    const parsed = parseXml("<instructions>\r\n  Line A\r\n    Line B\r\n</instructions>\r\n<task>T</task>\r\n");
    expect(normalize(parsed)).toEqual(normalize({ ...base, instructions: "Line A\n  Line B", task: "T" }));
  });

  it("tab-indented wrapper", () => {
    const parsed = parseXml("<prompt>\n\t<instructions>\n\t\tLine A\n\t\t\tLine B\n\t</instructions>\n</prompt>");
    expect(normalize(parsed)).toEqual(normalize({ ...base, instructions: "Line A\n\tLine B" }));
  });

  it("example tags sharing lines", () => {
    const parsed = parseXml(
      "<examples><example><input>\n      Q\n      </input><answer>A</answer></example></examples><instructions>I</instructions>"
    );
    expect(normalize(parsed)).toEqual(normalize({ ...base, instructions: "I", examples: [ex("Q", "", "A")] }));
  });

  it("underscore tag spellings", () => {
    const parsed = parseXml("<instructions>I</instructions>\n<output_format>JSON</output_format>\n<target_audience>Devs</target_audience>");
    expect(parsed.outputFormat).toBe("JSON");
    expect(parsed.targetAudience).toBe("Devs");
    expect(new RegExp(`<${tagPattern("output-format")}>`).test("<output_format>")).toBe(true);
  });

  it("agentCount is never below the number of roles; unknown values fall back", () => {
    const parsed = parseXml(
      '<instructions>x</instructions>\n<swarm-config topology="mesh" coordination="weighted" memory="local">\n  <agents count="2">\n    <agent type="coder" name="A">a</agent>\n    <agent type="tester" name="B">b</agent>\n    <agent type="bogus" name="C">c</agent>\n  </agents>\n</swarm-config>'
    );
    expect(parsed.swarmConfig?.agentCount).toBe(3);
    expect(parsed.swarmConfig?.agentRoles.map((r) => r.type)).toEqual(["coder", "tester", "custom"]);
  });

  it("empty or non-string input yields an empty prompt", () => {
    expect(normalize(parseXml(""))).toEqual(normalize(base));
    expect(normalize(parseXml(undefined as unknown as string))).toEqual(normalize(base));
  });
});

describe("parseXmlPartial", () => {
  it("returns only the sections present", () => {
    expect(parseXmlPartial("<task>T</task>")).toEqual({ task: "T" });
    expect(parseXmlPartial("no tags here")).toEqual({});
  });

  it("keeps examples when the block has no parseable items, clears them when empty", () => {
    expect(parseXmlPartial("<examples>free text</examples>")).not.toHaveProperty("examples");
    expect(parseXmlPartial("<examples>\n</examples>")).toEqual({ examples: [] });
  });

  it("PROMPT_TAGS covers every top-level tag the builder emits", () => {
    const xml = buildXml({
      ...base,
      instructions: "i",
      context: "c",
      constraints: "k",
      task: "t",
      targetAudience: "a",
      outputFormat: "o",
      examples: [ex("q", "r", "a")],
      technique: "react",
      swarmConfig: { topology: "star", coordinationStrategy: "majority", memoryScope: "project", agentCount: 1, agentRoles: [] },
    });
    const topLevel = [...xml.matchAll(/^<([a-z-]+)[\s>]/gm)].map((m) => m[1]);
    for (const tag of topLevel) expect(PROMPT_TAGS).toContain(tag);
  });
});
